---
# gather information from devices to use for parsing/configuration
- name: Get Interface Trunks From Device
  ios_command:
    commands:
      - show interface trunk
  register: trunk_output

# parse information from devices in preparation for processing changes
- name: Parse Trunk Data
  set_fact:
    trunk_parsed: "{{ trunk_output['stdout'][0] | parse_genie(command='show interfaces trunk', os=ansible_network_os) }}"
  delegate_to: localhost