---
- name: Deploy new vlan
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Gather Facts
      cisco.ios.ios_facts:
        gather_network_resources:
          - l2_interfaces
          - vlans

  # create a config backup prior to changes
    - name: Save device configuration
      ios_config:
        backup: true

    # import deploy vlan role
    - name: Include cisco_deploy_vlan role
      import_role:
        name: cisco_deploy_vlan
