---
- name: Deploy new vlan
  hosts: all
  gather_facts: true
  connection: network_cli

  tasks:
  # create a config backup prior to changes
    - name: Save device configuration
      ios_config:
        backup: true

    # bring in the genie parser plugin for processing show command results
    - name: Read in parse_genie role
      include_role:
        name: clay584.parse_genie

    # import deploy vlan role
    - name: Include deploy_vlan role
      import_role:
        name: Deploy_Vlan
