---
- name: Deploy new vlan
  hosts: all
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: ios

  tasks:
    - name: Gather Facts
      cisco.ios.ios_facts:
        gather_subset: all
      register: ios_facts

    - debug: var=ios_facts
