---
# gather information from devices to use for parsing/configuration
- name: Get VLANs From Device
  ios_command:
    commands:
      - show vlan
  register: vlan_output

# parse information from devices in preparation for processing changes
- name: Parse VLAN Data
  set_fact:
    vlan_parsed: "{{ vlan_output['stdout'][0] | parse_genie(command='show vlan', os=ansible_network_os ) }}"
  delegate_to: localhost

- name: Further Parse VLAN Data
  set_fact:
    vlan_further_parsed: "{{ vlan_parsed | json_query('*.*.vlan_id[]') }}"
